### ISSUE TITLE
prepare_embeddings() method not found in preprocessing.text_processing

### ISSUE THREAD

**Issue by bajajahsaas** [chaitanya2334/WLP-Parser#1]
test_manager.py using the prepare_embeddings(replace_digit=cfg.REPLACE_DIGITS) method, which is imported from preprocessing.text_processing. However, text_processing.py does not have any such method. Any thoughts?

**Comment by chaitanya2334** [comment]
ignore `corpus/test_manager.py`. Its using an older interface. 

`prepare_embeddings()` got moved to `corpus/WLPDataset.py` [here](https://github.com/chaitanya2334/WLP-Parser/blob/e6056e4d6420dc1f0f8ca832691a9961ac395b27/corpus/WLPDataset.py#L307).
