### ISSUE TITLE
ImportError: cannot import name 'Data' from 'corpus.WLPDataset'

### ISSUE THREAD

**Issue by bajajahsaas** [chaitanya2334/WLP-Parser#2]
While trying to run the code, I get the following error:

Traceback (most recent call last):
  File "Wlab_Parser/WLP-Parser/main.py", line 18, in <module>
    from corpus.WLPDataset import WLPDataset
  File "Wlab_Parser/WLP-Parser/corpus/WLPDataset.py", line 32, in <module>
    from preprocessing.text_processing import gen_list2id_dict
  File "Wlab_Parser/WLP-Parser/preprocessing/text_processing.py", line 7, in <module>
    from corpus.WLPDataset import Data
ImportError: cannot import name 'Data' from 'corpus.WLPDataset' (Wlab_Parser/WLP-Parser/corpus/WLPDataset.py)

Process finished with exit code 1

Also, I see cyclic dependencies of text_processing.py and WLPDataset.py where both these files have imports from each other.

**Comment by chaitanya2334** [comment]
https://github.com/chaitanya2334/WLP-Parser/blob/e6056e4d6420dc1f0f8ca832691a9961ac395b27/preprocessing/text_processing.py#L7

You might not have the latest commit. there is no such line in `text_processing.py`
